version: "3.12"

services:
  main:
    build:
      context: .
    command: ["uvicorn", "main:app" , "--host" , "0.0.0.0" , "--port", "8003"]
    volumes:
      - shared-data:/app/shared
    ports:
      - "8003:8003"
    restart: unless-stopped

  ws_main:
    build:
      context: .
    command: ["uvicorn", "ws_main:app" , "--host" , "0.0.0.0" , "--port", "8030"]
    volumes:
      - shared-data:/app/shared
    ports:
      - "8030:8030"
    restart: unless-stopped

volumes:
  shared-data:
