export const API_ROUTES = {
  auth: {
    login: "/login",
    userInfo: "/user-info",
  },
  product: {
    get: "/products",
    detail: "",
    insert: "/addproduct", 
    update: "/updateproduct",
    delete: "/deleteproduct",
    upload: "",
    suggest_product_id: "",
    suggest_product_name: "",
    suggest_serial_no: "",
  },
  product_type: {
    get: "/product-types",
    detail: "",
    insert: "/addprodtype", 
    update: "/updateprodtype",
    delete: "/deleteprodtype",
    upload: "",
    suggest_producttype_id: "",
    suggest_producttype_name: "",
  },
  defect_type: {
    get: "/defecttypes",
    detail: "",
    insert: "/adddefecttype", 
    update: "/updatedefecttype",
    delete: "/deletedefecttype",
    upload: "",
    suggest_defecttype_id: "",
    suggest_defecttype_name: "",
  },
  camera: {
    get: "/cameras",
    detail: "",
    insert: "/addcamera", 
    update: "/updatecamera",
    delete: "/deletecamera",
    upload: "",
    suggest_camera_id: "",
    suggest_camera_name: "",
    suggest_location: "",
  },
  user: {
    get: "/users",
    role: "/roles",
    detail: '',
    insert: "/adduser", 
    update: "/updateuser",
    delete: "/deleteuser",
    upload: "",
    suggest_userid: "",
    suggest_username: "",
  },
  role: {
    get: "/roles",
    detail: "",
    insert: "/addrole", 
    update: "/updaterole",
    delete: "/deleterole",
    upload: "",
    suggest_role_id: "",
    suggest_role_name: "",
  },
  permission: {
    get: "",
    detail: "",
    insert: "/add_permission", 
    update: "/update_permission",
    delete: "/update_permission",
  },
  menu: {
    get: "",
    detail: "",
    insert: "/add_menu", 
    update: "/update_menu",
    delete: "",
  },
  report_product: {
    get: "/productdefectresults",
    detail: "",
    insert: "/addreportproduct",
    update: "/updatereportproduct",
    upload: "",
  },
  report_defect: {
    get: "/defectsummary",
    suggest_lotno: "",
  },
  transaction: {
    get: "/transaction",
    suggest_lotno: "",
  },
  planning: {
    get: "/planning",
    detail: "",
    insert: "/addplanning", 
    update: "/updateplanning",
    delete: "/deleteplanning",
    upload: "", 
    suggest_planid: "",
    suggest_lotno: "",
    suggest_lineno: "",
    plans_confirmation: ""
  },
  detection_model: {
    get: "",
    detail: "",
    insert: "/adddetectionmodel", 
    update: "/updatedetectionmodel",
    delete: "/deletemodel",
    function: "",
    suggest_model: "",
    suggest_function: "",
  },
  dashboard: {
    total_products: "/totalprod",
    good_ng_ratio: "/goodngratio",
    top5_trends: "/top5trends",
    top5_defects: "/top5defects",
    ng_distribution: "/ngdistribution",
    defects_camera: "/defects-camera",
    products_list: "/products",
    cameras_list: "/cameras", 
    lines_list: "/lines",
  },
};
