export const API_ROUTES = {
  auth: {
    login: "/login",
    userInfo: "/user-info",
  },
  product: {
    get: "/products",
    detail: "",
    insert: "/add-product", 
    update: "/update-product",
    delete: "/delete-product",
    upload: "/upload-products",
    suggest_product_id: "/suggest-product-id",
    suggest_product_name: "/suggest-product-name",
    suggest_serial_no: "/suggest-serial-no",
  },
  product_type: {
    get: "/product-types",
    detail: "",
    insert: "/add-product-type", 
    update: "/update-product-type",
    delete: "/delete-product-type",
    upload: "/upload-product-types",
    suggest_producttype_id: "/suggest-producttype-id",
    suggest_producttype_name: "/suggest-producttype-name",
  },
  defect_type: {
    get: "/defect-types",
    detail: "",
    insert: "/add-defect-type", 
    update: "/update-defect-type",
    delete: "/delete-defect-type",
    upload: "/upload-defect-types",
    suggest_defecttype_id: "/suggest-defecttype-id",
    suggest_defecttype_name: "/suggest-defecttype-name",
  },
  camera: {
    get: "/cameras",
    detail: "",
    insert: "/add-camera", 
    update: "/update-camera",
    delete: "/delete-camera",
    upload: "/upload-cameras",
    suggest_camera_id: "/suggest-camera-id",
    suggest_camera_name: "/suggest-camera-name",
    suggest_location: "/suggest-camera-location",
  },
  user: {
    get: "/users",
    detail: '',
    insert: "/add-user", 
    update: "/update-user",
    delete: "/delete-user",
    upload: "/upload-users",
    suggest_userid: "/suggest-userid",
    suggest_username: "/suggest-username",
  },
  role: {
    get: "/roles",
    detail: "",
    insert: "/add-role", 
    update: "/update-role",
    delete: "/delete-role",
    upload: "/upload-roles",
    suggest_role_name: "/suggest-role-name",
  },
  permission: {
    get: "/permissions", // PUT request with roleid parameter (ตาม backend)
    detail: "",
    insert: "/add_permission", 
    update: "/update_permission", // PUT with permissionid parameter
    delete: "/delete_permission", // DELETE with permissionid parameter
  },
  // แก้ไข menu endpoints ตามที่มีจริงใน backend  
  menu: {
    get: "/menu", // POST request (ตาม backend)
    detail: "",
    insert: "/add_menu", 
    update: "/update_menu", // PUT with menuid parameter
    delete: "",
  },
  report_product: {
    get: "/report-product-defect",
    detail: "/report-product-defect-detail",
    update: "/update-product-detail",
  },
  report_defect: {
    get: "/report-defect-summary",
    suggest_lotno: "/suggest-defect-lotno",
  },
  transaction: {
    get: "/transaction",
    suggest_lotno: "/suggest-transaction-lotno",
  },
  planning: {
    get: "/planning",
    detail: "",
    insert: "/add-planning", 
    update: "/update-planning",
    delete: "/delete-planning",
    upload: "/upload-planning", 
    suggest_planid: "/suggest-planid",
    suggest_lotno: "/suggest-plan-lotno",
    suggest_lineid: "/suggest-plan-lineid",
    plans_confirmation: ""
  },
  detection_model: {
    get: "/detection-model",
    detail: "/model-detail", 
    insert: "/add-model", 
    delete: "/delete-model",
    update_step1: "/update-model-step1",
    update_step2: "/update-model-step2",
    update_step3: "/update-model-step3",
    update_step4: "/update-model-step4",
    model_function: "/model-function",
    model_version: "/model-version",
    model_image: "/model-image",
    model_camera: "/model-camera",
    function: "/function",
    label_class: "/label-class",
    suggest_model: "/suggest-modelname",
    suggest_function: "/suggest-function",
  },
  dashboard: {
    total_products: "/dashboard-totalproduct",
    good_ng_ratio: "/dashboard-goodngratio",
    top5_trends: "/dashboard-top5trends",
    top5_defects: "/dashboard-top5defects",
    ng_distribution: "/dashboard-ngdistribution",
    defects_camera: "/dashboard-defectscamera",
    products_list: "/filter-products",
    cameras_list: "/filter-cameras", 
    lines_list: "/filter-lines",
  },
};
