export const API_ROUTES = {
  auth: {
    login: "/login",
    userInfo: "/user-info",
  },
  product: {
    get: "/products",
    detail: "",
    insert: "/add-product", 
    update: "/update-product",
    delete: "/delete-product",
    upload: "",
    suggest_product_id: "",
    suggest_product_name: "",
    suggest_serial_no: "",
  },
  product_type: {
    get: "/product-types",
    detail: "",
    insert: "/add-product-type", 
    update: "/update-product-type",
    delete: "/delete-product-type",
    upload: "",
    suggest_producttype_id: "",
    suggest_producttype_name: "",
  },
  defect_type: {
    get: "/defect-types",
    detail: "",
    insert: "/add-defect-type", 
    update: "/update-defect-type",
    delete: "/delete-defect-type",
    upload: "",
    suggest_defecttype_id: "",
    suggest_defecttype_name: "",
  },
  camera: {
    get: "/cameras",
    detail: "",
    insert: "/add-camera", 
    update: "/update-camera",
    delete: "/delete-camera",
    upload: "",
    suggest_camera_id: "",
    suggest_camera_name: "",
    suggest_location: "",
  },
  user: {
    get: "/users",
    role: "/roles",
    detail: '',
    insert: "/add-user", 
    update: "/update-user",
    delete: "/delete-user",
    upload: "",
    suggest_userid: "",
    suggest_username: "",
  },
  role: {
    get: "/roles",
    detail: "",
    insert: "/add-role", 
    update: "/update-role",
    delete: "/delete-role",
    upload: "",
    suggest_role_id: "",
    suggest_role_name: "",
  },
  permission: {
    get: "",
    detail: "",
    insert: "/add_permission", 
    update: "/update_permission",
    delete: "/delete_permission",
  },
  menu: {
    get: "",
    detail: "",
    insert: "/add_menu", 
    update: "/update_menu",
    delete: "",
  },
  report_product: {
    get: "/report-product-defect",
    detail: "/report-product-defect-detail",
    update: "/update-product-detail",
    upload: "",
  },
  report_defect: {
    get: "/report-defect-summary",
    suggest_lotno: "",
  },
  transaction: {
    get: "/transaction",
    suggest_lotno: "",
  },
  planning: {
    get: "/planning",
    detail: "",
    insert: "/add-planning", 
    update: "/update-planning",
    delete: "/delete-planning",
    upload: "", 
    suggest_planid: "",
    suggest_lotno: "",
    suggest_lineno: "",
    plans_confirmation: ""
  },
  detection_model: {
    get: "/detection-model",
    detail: "/model-detail", 
    insert: "/add-model", 
    // update: "/update-model",
    delete: "/delete-model",
    update_step1: "/update-model-step1",
    update_step2: "/update-model-step2",
    update_step3: "/update-model-step3",
    update_step4: "/update-model-step4",
    model_function: "/model-function",
    model_version: "/model-version",
    model_image: "/model-image",
    model_camera: "/model-camera",
    function: "/function",
    label_class: "/label-class",
    suggest_model: "",
    suggest_function: "",
  },
  dashboard: {
    total_products: "/dashboard-totalproduct",
    good_ng_ratio: "/dashboard-goodngratio",
    top5_trends: "/dashboard-top5trends",
    top5_defects: "/dashboard-top5defects",
    ng_distribution: "/dashboard-ngdistribution",
    defects_camera: "/dashboard-defectscamera",
    products_list: "/filter-products",
    cameras_list: "/filter-cameras", 
    lines_list: "/filter-lines",
  },
};
