version: '3.8'
services:
  nextjs-app:
    container_name: inspection
    build:
      context: .  
      dockerfile: src/Dockerfile  
    ports:
      - "3032:3000"
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - env_product-inspection_inspection-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
networks:
  env_product-inspection_inspection-network:
    external: true