version: '3.8'
services:
  nextjs-app:
    container_name: inspection
    build:
      context: .  
      dockerfile: src/Dockerfile  
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - env_product-inspection_inspection-network  

networks:
  env_product-inspection_inspection-network:
    external: true  