version: '3.8'

services:
  nextjs-app:
    image: inspection
    container_name: inspection
    build:
      context: .  
      dockerfile: src/Dockerfile  
    ports:
      - "3032:3000"
    volumes:
      - ./:/app 
      - /app/node_modules  
    environment:
      - NODE_ENV=production 
    networks:
      - inspection-network


networks:
  inspection-network:
